"""initial schema

Revision ID: 8eb232c46b67
Revises: 
Create Date: 2026-06-11 08:04:17.554466

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8eb232c46b67'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('score_history',
    sa.Column('stock_code', sa.String(length=10), nullable=False),
    sa.Column('trade_date', sa.Date(), nullable=False),
    sa.Column('total_score', sa.Numeric(precision=5, scale=1), nullable=True),
    sa.Column('technical_score', sa.Numeric(precision=5, scale=1), nullable=True),
    sa.Column('chip_score', sa.Numeric(precision=5, scale=1), nullable=True),
    sa.Column('fundamental_score', sa.Numeric(precision=5, scale=1), nullable=True),
    sa.Column('sentiment_score', sa.Numeric(precision=5, scale=1), nullable=True),
    sa.PrimaryKeyConstraint('stock_code', 'trade_date')
    )
    op.create_index('ix_score_history_code_date', 'score_history', ['stock_code', 'trade_date'], unique=False)
    op.create_table('sentiment_data',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('stock_code', sa.String(length=10), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('sentiment_score', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('confidence', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.Column('llm_summary', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sentiment_data_stock_code'), 'sentiment_data', ['stock_code'], unique=False)
    op.create_index(op.f('ix_sentiment_data_time'), 'sentiment_data', ['time'], unique=False)
    op.create_table('stocks',
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('market', sa.String(length=10), nullable=True),
    sa.Column('stock_type', sa.String(length=10), nullable=True),
    sa.Column('industry_code', sa.String(length=10), nullable=True),
    sa.Column('industry_name', sa.String(length=100), nullable=True),
    sa.Column('market_cap', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('listed_date', sa.Date(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('chip_data',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('stock_code', sa.String(length=10), nullable=False),
    sa.Column('trade_date', sa.Date(), nullable=False),
    sa.Column('proprietary_buy', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('proprietary_sell', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('proprietary_net', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('foreign_buy', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('foreign_sell', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('foreign_net', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('trust_buy', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('trust_sell', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('trust_net', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('gw_volume', sa.Numeric(precision=15, scale=0), nullable=True),
    sa.Column('margin_balance', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('margin_buy', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('margin_sell', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('margin_net', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['stock_code'], ['stocks.code'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chip_data_stock_code'), 'chip_data', ['stock_code'], unique=False)
    op.create_index(op.f('ix_chip_data_trade_date'), 'chip_data', ['trade_date'], unique=False)
    op.create_table('daily_bars',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('stock_code', sa.String(length=10), nullable=False),
    sa.Column('trade_date', sa.Date(), nullable=False),
    sa.Column('open_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('high_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('low_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('close_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('adjusted_close', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('volume', sa.Numeric(precision=18, scale=0), nullable=True),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('turn_rate', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.ForeignKeyConstraint(['stock_code'], ['stocks.code'], ),
    sa.PrimaryKeyConstraint('id'),
    unique_constraints=[]
    )
    op.create_index(op.f('ix_daily_bars_stock_code'), 'daily_bars', ['stock_code'], unique=False)
    op.create_index(op.f('ix_daily_bars_trade_date'), 'daily_bars', ['trade_date'], unique=False)
    op.create_table('holdings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('stock_code', sa.String(length=10), nullable=False),
    sa.Column('stock_name', sa.String(length=100), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('avg_cost', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('purchase_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'stock_code', name='uq_user_stock')
    )
    op.create_table('industry_chains',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('parent_industry', sa.String(length=100), nullable=False),
    sa.Column('sub_industry', sa.String(length=100), nullable=False),
    sa.Column('stock_code', sa.String(length=10), nullable=False),
    sa.Column('relation_type', sa.String(length=20), nullable=False),
    sa.Column('weight', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['stock_code'], ['stocks.code'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_industry_chains_parent_industry'), 'industry_chains', ['parent_industry'], unique=False)
    op.create_index(op.f('ix_industry_chains_relation_type'), 'industry_chains', ['relation_type'], unique=False)
    op.create_table('minute_bars',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('stock_code', sa.String(length=10), nullable=False),
    sa.Column('bar_time', sa.Date(), nullable=False),
    sa.Column('interval_minutes', sa.Integer(), nullable=False),
    sa.Column('open_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('high_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('low_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('close_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('volume', sa.Numeric(precision=18, scale=0), nullable=True),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['stock_code'], ['stocks.code'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_minute_bars_bar_time'), 'minute_bars', ['bar_time'], unique=False)
    op.create_index(op.f('ix_minute_bars_stock_code'), 'minute_bars', ['stock_code'], unique=False)
    op.create_table('tdcc_holder_data',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('stock_code', sa.String(length=10), nullable=False),
    sa.Column('week_date', sa.Date(), nullable=False),
    sa.Column('holder_400_count', sa.Integer(), nullable=True),
    sa.Column('holder_400_shares', sa.Numeric(precision=15, scale=0), nullable=True),
    sa.Column('holder_400_ratio', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('holder_1000_count', sa.Integer(), nullable=True),
    sa.Column('holder_1000_shares', sa.Numeric(precision=15, scale=0), nullable=True),
    sa.Column('holder_1000_ratio', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('holder_5000_count', sa.Integer(), nullable=True),
    sa.Column('holder_5000_shares', sa.Numeric(precision=15, scale=0), nullable=True),
    sa.Column('holder_5000_ratio', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('float_shares', sa.Numeric(precision=15, scale=0), nullable=True),
    sa.ForeignKeyConstraint(['stock_code'], ['stocks.code'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tdcc_holder_data_stock_code'), 'tdcc_holder_data', ['stock_code'], unique=False)
    op.create_index(op.f('ix_tdcc_holder_data_week_date'), 'tdcc_holder_data', ['week_date'], unique=False)
    op.create_table('trade_journals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('journal_date', sa.Date(), nullable=False),
    sa.Column('market_summary', sa.Text(), nullable=True),
    sa.Column('key_breakouts', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('potential_risks', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('recommendations', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('llm_analysis', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('watchlist',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('stock_code', sa.String(length=10), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('added_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'stock_code', name='uq_watchlist_user_stock')
    )
    op.create_table('holding_diagnostics',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('holding_id', sa.UUID(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('technical_score', sa.Integer(), nullable=True),
    sa.Column('chip_score', sa.Integer(), nullable=True),
    sa.Column('fundamental_score', sa.Integer(), nullable=True),
    sa.Column('sentiment_score', sa.Integer(), nullable=True),
    sa.Column('health_level', sa.String(length=20), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('analyzed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['holding_id'], ['holdings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('holding_diagnostics')
    op.drop_table('watchlist')
    op.drop_table('trade_journals')
    op.drop_index(op.f('ix_tdcc_holder_data_week_date'), table_name='tdcc_holder_data')
    op.drop_index(op.f('ix_tdcc_holder_data_stock_code'), table_name='tdcc_holder_data')
    op.drop_table('tdcc_holder_data')
    op.drop_index(op.f('ix_minute_bars_stock_code'), table_name='minute_bars')
    op.drop_index(op.f('ix_minute_bars_bar_time'), table_name='minute_bars')
    op.drop_table('minute_bars')
    op.drop_index(op.f('ix_industry_chains_relation_type'), table_name='industry_chains')
    op.drop_index(op.f('ix_industry_chains_parent_industry'), table_name='industry_chains')
    op.drop_table('industry_chains')
    op.drop_table('holdings')
    op.drop_index(op.f('ix_daily_bars_trade_date'), table_name='daily_bars')
    op.drop_index(op.f('ix_daily_bars_stock_code'), table_name='daily_bars')
    op.drop_table('daily_bars')
    op.drop_index(op.f('ix_chip_data_trade_date'), table_name='chip_data')
    op.drop_index(op.f('ix_chip_data_stock_code'), table_name='chip_data')
    op.drop_table('chip_data')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('stocks')
    op.drop_index(op.f('ix_sentiment_data_time'), table_name='sentiment_data')
    op.drop_index(op.f('ix_sentiment_data_stock_code'), table_name='sentiment_data')
    op.drop_table('sentiment_data')
    op.drop_index('ix_score_history_code_date', table_name='score_history')
    op.drop_table('score_history')
    # ### end Alembic commands ###
